# Generated by Django 4.2.8 on 2024-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTrailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('EventName', models.CharField(max_length=100)),
                ('EventType', models.CharField(max_length=30)),
                ('EventTime', models.DateTimeField()),
                ('sourceIPAddr', models.GenericIPAddressField()),
            ],
        ),
    ]
