# Generated by Django 4.2.8 on 2024-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTrailCndevRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('EventName', models.CharField(max_length=50)),
                ('UserAgent', models.CharField(max_length=200)),
                ('ResourceName', models.CharField(max_length=200)),
                ('ResourceType', models.CharField(max_length=200)),
                ('EventTime', models.DateTimeField()),
                ('sourceIPAddr', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'cloudtrailcndev',
            },
        ),
        migrations.CreateModel(
            name='CloudTrailCnprodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('EventName', models.CharField(max_length=50)),
                ('UserAgent', models.CharField(max_length=200)),
                ('ResourceName', models.CharField(max_length=200)),
                ('ResourceType', models.CharField(max_length=200)),
                ('EventTime', models.DateTimeField()),
                ('sourceIPAddr', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'cloudtrailcnprod',
            },
        ),
    ]
