# Generated by Django 4.2.8 on 2024-03-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtrailcndevrecord',
            name='RequestParameters',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='cloudtrailcnprodrecord',
            name='RequestParameters',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
