# Generated by Django 4.2.8 on 2024-02-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloudtrailrecord',
            table='cloudtrailrecord',
        ),
    ]
