# Generated by Django 4.2.8 on 2024-04-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0002_cloudtrailcndevrecord_requestparameters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTrailCn09Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('EventName', models.CharField(max_length=50)),
                ('UserAgent', models.CharField(max_length=200)),
                ('ResourceName', models.CharField(max_length=200)),
                ('ResourceType', models.CharField(max_length=200)),
                ('EventTime', models.DateTimeField()),
                ('sourceIPAddr', models.GenericIPAddressField()),
                ('RequestParameters', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'db_table': 'cloudtrailcn09',
            },
        ),
    ]
