# Generated by Django 4.2.8 on 2024-02-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0002_alter_cloudtrailrecord_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtrailrecord',
            name='UserAgent',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
