# Generated by Django 4.2.8 on 2024-02-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0003_cloudtrailrecord_useragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='EventName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='UserAgent',
            field=models.CharField(default='-', max_length=60),
        ),
    ]
