# Generated by Django 4.2.8 on 2024-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0004_alter_cloudtrailrecord_eventname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='UserAgent',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
