# Generated by Django 4.2.8 on 2024-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0005_alter_cloudtrailrecord_useragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='UserAgent',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
