# Generated by Django 4.2.8 on 2024-02-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0006_alter_cloudtrailrecord_useragent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudtrailrecord',
            old_name='EventType',
            new_name='Resource',
        ),
    ]
