# Generated by Django 4.2.8 on 2024-02-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudtrailapp", "0007_rename_eventtype_cloudtrailrecord_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudtrailrecord",
            name="Resource",
            field=models.CharField(default="-", max_length=30),
        ),
    ]
