# Generated by Django 4.2.8 on 2024-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0009_rename_resource_cloudtrailrecord_resourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtrailrecord',
            name='ResourceType',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='ResourceName',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
