# Generated by Django 4.2.8 on 2024-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudtrailapp', '0010_cloudtrailrecord_resourcetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='ResourceName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='ResourceType',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cloudtrailrecord',
            name='UserAgent',
            field=models.CharField(max_length=200),
        ),
    ]
